In [1]:
import numpy as np
import pandas as pd
import torch
from torch import nn
import torch.nn.functional as F

In [74]:
import torch.optim as optim

In [78]:
params= torch.tensor([1.0, 0.0], requires_grad=True)
optimizer= optim.SGD([params],lr=1e-3)

In [2]:
t= torch.ones(3,4)

In [3]:
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
t.size()

torch.Size([3, 4])

In [5]:
type(t)

torch.Tensor

In [6]:
t=torch.tensor(3)

In [7]:
t

tensor(3)

In [8]:
type(t)

torch.Tensor

In [9]:
t.size()

torch.Size([])

In [10]:
t=torch.tensor([[3,1,4],[5,3,5]])
t

tensor([[3, 1, 4],
        [5, 3, 5]])

In [12]:
t=torch.rand(2,5)


In [13]:
t

tensor([[0.7956, 0.9264, 0.3323, 0.7661, 0.4752],
        [0.4637, 0.6778, 0.9278, 0.6929, 0.1041]])

In [16]:
t.max()

tensor(0.9278)

In [18]:
t.shape

torch.Size([2, 5])

In [28]:
t.view(10)

tensor([0.7956, 0.9264, 0.3323, 0.7661, 0.4752, 0.4637, 0.6778, 0.9278, 0.6929,
        0.1041])

In [29]:
flat_t=torch.rand(9)
view_t=flat_t.view(3,3)
reshape_t=flat_t.reshape(3,3)

In [30]:
flat_t

tensor([0.8895, 0.9528, 0.8811, 0.9729, 0.0908, 0.3457, 0.8372, 0.6041, 0.1430])

In [31]:
view_t

tensor([[0.8895, 0.9528, 0.8811],
        [0.9729, 0.0908, 0.3457],
        [0.8372, 0.6041, 0.1430]])

In [32]:
reshape_t

tensor([[0.8895, 0.9528, 0.8811],
        [0.9729, 0.0908, 0.3457],
        [0.8372, 0.6041, 0.1430]])

In [35]:
torch.cuda.is_available()

True

In [36]:
t=torch.rand([9], requires_grad=True)

In [37]:
t

tensor([0.6748, 0.8652, 0.2479, 0.8507, 0.7765, 0.5985, 0.0714, 0.7396, 0.1750],
       requires_grad=True)

In [45]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.h1=nn.Linear(1,10)
        self.o1=nn.Linear(10,1)
        
        self.relu=nn.ReLU()
    
    def forward(self, x):
        hidden=self.h1(x)
        activation=self.relu(hidden)
        output=self.o1(activation)
        return output
    
net=Net()

In [46]:
net.h1.weight

Parameter containing:
tensor([[-0.7860],
        [ 0.0311],
        [ 0.2749],
        [-0.9380],
        [ 0.1081],
        [ 0.1372],
        [-0.2703],
        [-0.4716],
        [-0.6160],
        [-0.1550]], requires_grad=True)

In [49]:
net.h1.bias

Parameter containing:
tensor([-0.6610, -0.1030, -0.4649, -0.7895,  0.4848,  0.8170,  0.3905,  0.5981,
        -0.8035, -0.0545], requires_grad=True)

In [69]:
#output=net(input)
loss_fn=nn.MSELoss()
#loss=loss_fn(output, target)

In [61]:
net.zero_grad()

print('h1.bias.grad before backward prop')
print(net.h1.bias.grad)

#loss.backward()

print('h1.bias.grad after backprop')
print(net.h1.bias.grad)

h1.bias.grad before backward prop
None
h1.bias.grad after backprop
None


In [70]:
def training_loop(n_epochs, optimizer, model, loss_fn, inputs, target):
    for epoch in range(1, n_epochs +1 ):
        optimizer.zero_grad()
        output=net(inputs)
        loss=loss_fn(output, target)
        loss.backward()
        optimizer.step()
        if epoch %100 ==0:
            print('Epoch %d, Loss %f' %(epoch,float(loss)))
    return params

In [71]:
x_t=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]
y_t=[1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0, 121.0]

In [81]:
training_loop(n_epochs=600, optimizer=optimizer, model=net, loss_fn=nn.MSELoss(), inputs=x_t, target=y_t)

AttributeError: 'list' object has no attribute 'dim'