In [1]:
import numpy as np
import torch 
from torch import nn
import torch.nn.functional as F

In [2]:
with open('data/anna.txt','r') as f:
    text=f.read()

In [6]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

In [8]:
#tokenization

chars=tuple(set(text))
int2char=dict(enumerate(chars))
char2int= {ch: ii for ii,ch in int2char.items()}

encoded =np.array([char2int[ch] for ch in text])



In [9]:
int2char.items()

dict_items([(0, '6'), (1, 'o'), (2, ';'), (3, 'W'), (4, '?'), (5, '2'), (6, '/'), (7, 'R'), (8, 'S'), (9, ','), (10, '_'), (11, 'Q'), (12, '`'), (13, '*'), (14, '@'), (15, 'p'), (16, 'E'), (17, '7'), (18, 'e'), (19, 'l'), (20, '-'), (21, '('), (22, 'L'), (23, '!'), (24, 'A'), (25, 'O'), (26, '3'), (27, 's'), (28, 'K'), (29, ' '), (30, 'q'), (31, 'm'), (32, '"'), (33, 'j'), (34, 'k'), (35, "'"), (36, 'y'), (37, 'i'), (38, 'F'), (39, 'M'), (40, '&'), (41, '9'), (42, 'n'), (43, ')'), (44, '1'), (45, 'c'), (46, 't'), (47, 'g'), (48, 'd'), (49, 'f'), (50, 'G'), (51, ':'), (52, 'T'), (53, 'I'), (54, 'v'), (55, '4'), (56, '8'), (57, 'Y'), (58, '%'), (59, '\n'), (60, 'H'), (61, '0'), (62, 'u'), (63, 'b'), (64, '5'), (65, 'Z'), (66, 'N'), (67, 'P'), (68, 'h'), (69, 'C'), (70, 'w'), (71, 'B'), (72, 'r'), (73, '$'), (74, '.'), (75, 'D'), (76, 'a'), (77, 'z'), (78, 'x'), (79, 'J'), (80, 'X'), (81, 'U'), (82, 'V')])

In [10]:
encoded[:100]

array([69, 68, 76, 15, 46, 18, 72, 29, 44, 59, 59, 59, 60, 76, 15, 15, 36,
       29, 49, 76, 31, 37, 19, 37, 18, 27, 29, 76, 72, 18, 29, 76, 19, 19,
       29, 76, 19, 37, 34, 18,  2, 29, 18, 54, 18, 72, 36, 29, 62, 42, 68,
       76, 15, 15, 36, 29, 49, 76, 31, 37, 19, 36, 29, 37, 27, 29, 62, 42,
       68, 76, 15, 15, 36, 29, 37, 42, 29, 37, 46, 27, 29,  1, 70, 42, 59,
       70, 76, 36, 74, 59, 59, 16, 54, 18, 72, 36, 46, 68, 37, 42])

In [15]:
char2int.items()

dict_items([('6', 0), ('o', 1), (';', 2), ('W', 3), ('?', 4), ('2', 5), ('/', 6), ('R', 7), ('S', 8), (',', 9), ('_', 10), ('Q', 11), ('`', 12), ('*', 13), ('@', 14), ('p', 15), ('E', 16), ('7', 17), ('e', 18), ('l', 19), ('-', 20), ('(', 21), ('L', 22), ('!', 23), ('A', 24), ('O', 25), ('3', 26), ('s', 27), ('K', 28), (' ', 29), ('q', 30), ('m', 31), ('"', 32), ('j', 33), ('k', 34), ("'", 35), ('y', 36), ('i', 37), ('F', 38), ('M', 39), ('&', 40), ('9', 41), ('n', 42), (')', 43), ('1', 44), ('c', 45), ('t', 46), ('g', 47), ('d', 48), ('f', 49), ('G', 50), (':', 51), ('T', 52), ('I', 53), ('v', 54), ('4', 55), ('8', 56), ('Y', 57), ('%', 58), ('\n', 59), ('H', 60), ('0', 61), ('u', 62), ('b', 63), ('5', 64), ('Z', 65), ('N', 66), ('P', 67), ('h', 68), ('C', 69), ('w', 70), ('B', 71), ('r', 72), ('$', 73), ('.', 74), ('D', 75), ('a', 76), ('z', 77), ('x', 78), ('J', 79), ('X', 80), ('U', 81), ('V', 82)])

In [18]:
# pre processing 
def one_hot_encode(arr,n_labels):
    one_hot=np.zeros((arr.size,n_labels),dtype=np.float32)
    one_hot[np.arange(one_hot.shape[0]),arr.flatten()]=1.
    one_hot=one_hot.reshape((*arr.shape, n_labels))
    return one_hot

In [19]:
#testing function
test_seq=np.array([[3,4,1,4]])
one_hot=one_hot_encode(test_seq,8)
print(test_seq)
print(one_hot)

[[3 4 1 4]]
[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]]]
